version: '3.9'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db_postgres:/var/lib/postgresql/data
    ports:
      - "6666:5432"

volumes:
   db_postgres:
